### ISSUE TITLE
Can't delete Code:

### ISSUE THREAD

**Issue by simonesolda** [schumijo/homeassistant-addons#8]
Component 0.1.5
Can't delete Code: line.
If I delete it it gets re-created.
If I set a code, code_arm_required: false  code_disarm_required: false are ignored and always show a code selector panel under alarm.

**Comment by arag00rn** [comment]
Same problem here.
Actually at beginning was working fine. Then I guess restarted HASSIO.

**Comment by gmarchett** [comment]
here too

**Comment by schumijo** [comment]
For my personal use, I keep the default configuration and code selector panel is not shown. Can you try it ?

**Comment by gmarchett** [comment]
Tried but it doesn’t work. Is it possible that package is old? It seems that on original repo there are some updates in last months, maybe downloading from HACS we have an old version.
Thanks a lot

**Comment by schumijo** [comment]
Sorry @gmarchett I don't understand !?
This is an addon so you can't use HACS. About original repo, are you talking about Minims one ? If yes, last update was done was done few hours ago.

Which version are you using ? Dev-addon or not ?

**Comment by simonesolda** [comment]
I fixed it using:
homeassistant_config:
  code: 0
  code_arm_required: false
  code_disarm_required: false

**Comment by arag00rn** [comment]
@simonesolda workaround works! Thank you

**Comment by gmarchett** [comment]
@simonesolda thanks, this trick works fine!
@schumijo: i've updated last version (i'm using dev one) and now all it's fine, thanks a lot for your support!

**Comment by schumijo** [comment]
I'm sorry guys. I just upgrade my HassOS from 6.2 to 6.4 and I am now able to reproduce the problem. 
I will do some investigations

**Comment by teocannata** [comment]
Here the same, I will use the workaround... Thank you!

**Comment by schumijo** [comment]
I changed default value to 0 and updated documentation
